package com.example.bandlink.service;
import com.example.bandlink.dto.MessageRequests; import com.example.bandlink.entity.*; import com.example.bandlink.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class MessageService { private final UserRepository users; private final ConversationRepository conversations; private final MessageRepository messages; private final Clock clock;
 public MessageService(UserRepository u,ConversationRepository c,MessageRepository m){this(u,c,m,Clock.systemDefaultZone());} MessageService(UserRepository u,ConversationRepository c,MessageRepository m,Clock k){users=u;conversations=c;messages=m;clock=k==null?Clock.systemDefaultZone():k;}
 @Transactional public Message send(Long senderId,Long recipientId,MessageRequests.Send r){User s=verified(senderId),t=active(recipientId); if(senderId.equals(recipientId))throw new RuleViolationException("自分自身には送信できません"); Conversation c=conversation(s,t); Message msg=messages.save(new Message(c,s,r.content().trim(),r.imageUrl(),now())); c.touch(now()); return msg;}
 @Transactional public List<Message> messages(Long userId,Long conversationId){Conversation c=conversations.findById(conversationId).orElseThrow(()->new RuleViolationException("会話が見つかりません")); if(!c.includes(userId))throw new RuleViolationException("会話を閲覧できません"); return messages.findByConversationIdOrderByCreatedAtAsc(conversationId);}
 private Conversation conversation(User a,User b){Long x=a.getId(),y=b.getId(); User first=x<y?a:b; User second=x<y?b:a; return conversations.findByUserAIdAndUserBId(first.getId(),second.getId()).orElseGet(()->conversations.save(new Conversation(first,second,now())));}
 private User verified(Long id){User u=active(id);if(!u.isEmailVerified())throw new RuleViolationException("メールアドレスの確認が必要です");return u;} private User active(Long id){User u=users.findById(id).orElseThrow(()->new RuleViolationException("ユーザーが見つかりません"));if(!u.isActive())throw new RuleViolationException("現在この操作は利用できません");return u;} private LocalDateTime now(){return LocalDateTime.now(clock);} public static class RuleViolationException extends RuntimeException{public RuleViolationException(String m){super(m);}}
}
