\encoding UTF8
\set ON_ERROR_STOP on
-- DESIGN ONLY / NOT EXECUTED. psql -X -d band_link_release_test -v qa_password_hash=... -f this-file
-- The first application startup creates public tables and masters. Stop the application before seeding.
BEGIN;
SET LOCAL search_path = public;
SET LOCAL TIME ZONE 'Asia/Tokyo';
DO $$ BEGIN
  IF current_database() <> 'band_link_release_test' THEN
    RAISE EXCEPTION 'Refusing seed: only dedicated band_link_release_test is permitted';
  END IF;
  IF to_regclass('public.users') IS NULL OR to_regclass('public.feedback') IS NULL THEN
    RAISE EXCEPTION 'Start the test application once to initialize the full schema, then stop it';
  END IF;
  IF to_regclass('public.qa_release_fixture') IS NULL AND EXISTS (SELECT 1 FROM public.users) THEN
    RAISE EXCEPTION 'First seed requires an empty users table; existing data will not be adopted';
  END IF;
END $$;
CREATE TABLE IF NOT EXISTS public.qa_release_fixture (
  singleton boolean PRIMARY KEY CHECK(singleton), suite text NOT NULL,
  anchor timestamp NOT NULL, manifest_version integer NOT NULL
);
DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM qa_release_fixture WHERE suite <> 'Band Link disposable release QA') THEN
    RAISE EXCEPTION 'Unexpected database ownership marker';
  END IF;
END $$;
-- No CASCADE: a newly introduced dependency must fail visibly rather than be silently cleared.
-- This is a COMPLETE reset of disposable application rows in the guarded QA DB, including rows
-- created by earlier test cases. It never connects to or modifies band_link. Master rows remain.
TRUNCATE feedback, reports, messages, conversations, notifications, blocks,
  search_histories, email_verification_tokens, password_reset_tokens, line_accounts,
  post_images, post_age_ranges, post_parts, post_genres, post_stances, post_prefectures,
  posts, user_parts, user_genres, user_stances, user_prefectures, users RESTART IDENTITY;
INSERT INTO qa_release_fixture VALUES (true,'Band Link disposable release QA',localtimestamp,1)
ON CONFLICT(singleton) DO UPDATE SET anchor=EXCLUDED.anchor, manifest_version=EXCLUDED.manifest_version;
CREATE TEMP TABLE qa_config ON COMMIT DROP AS SELECT :'qa_password_hash'::text AS password_hash, anchor FROM qa_release_fixture;
DO $$ BEGIN
  IF (SELECT password_hash FROM qa_config) !~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$' THEN
    RAISE EXCEPTION 'Supply qa_password_hash generated by ReleasePasswordHash.java';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM parts WHERE name='ギター') OR
     NOT EXISTS(SELECT 1 FROM parts WHERE name='ベース') OR
     NOT EXISTS(SELECT 1 FROM genres WHERE name='ポップス') OR
     NOT EXISTS(SELECT 1 FROM genres WHERE name='ジャズ') OR
     NOT EXISTS(SELECT 1 FROM stances WHERE name='趣味で楽しみたい') OR
     NOT EXISTS(SELECT 1 FROM prefectures WHERE name='東京都') OR
     NOT EXISTS(SELECT 1 FROM prefectures WHERE name='大阪府') OR
     NOT EXISTS(SELECT 1 FROM prefectures WHERE name='神奈川県') THEN
    RAISE EXCEPTION 'Expected application masters absent; do not invent replacement master IDs';
  END IF;
END $$;
CREATE TEMP TABLE qa_actors(n integer, label text) ON COMMIT DROP;
INSERT INTO qa_actors VALUES
 (1,'unverified'),(2,'general'),(3,'incomplete'),(4,'complete'),(5,'wanted'),(6,'join'),
 (7,'sender'),(8,'receiver'),(9,'blocker'),(10,'blocked'),(11,'suspended'),
 (13,'admin'),(14,'images'),(15,'age-min'),(16,'age-max'),(17,'edit-locked'),
 (18,'edit-ready'),(19,'rank-locked'),(20,'rank-ready'),(21,'expiry'),
 (22,'withdraw-target'),(23,'third-party'),(24,'legacy-withdrawn'),(25,'line-linked');
-- 910012 is intentionally ABSENT: completed physical withdrawal is not a WITHDRAWN row.
INSERT INTO users(id,username,email,password_hash,email_verified_at,status,role,age,gender,bio,
 experience_years,last_edited_at,last_rank_boosted_at,last_login_at,last_seen_at,created_at)
SELECT 910000+n,'QA_RELEASE_'||label,'qa-release-'||label||'@example.test',q.password_hash,
 CASE WHEN n=1 THEN NULL ELSE q.anchor-interval '2 days' END,
 CASE WHEN n=11 THEN 'SUSPENDED' WHEN n=24 THEN 'WITHDRAWN' ELSE 'ACTIVE' END,
 CASE WHEN n=13 THEN 'ADMIN' ELSE 'USER' END,
 CASE WHEN n IN(3,24,25) THEN NULL WHEN n=15 THEN 0 WHEN n=16 THEN 120 ELSE 28 END,
 CASE WHEN n IN(3,24,25) THEN NULL WHEN n%2=0 THEN '女性' ELSE '男性' END,
 CASE WHEN n IN(3,24,25) THEN NULL WHEN n=4 THEN repeat('紹介',500) ELSE 'QA_RELEASE 合成プロフィール' END,
 CASE WHEN n IN(3,24,25) THEN NULL WHEN n=15 THEN 0 WHEN n=16 THEN 100 ELSE 5 END,
 CASE WHEN n=17 THEN q.anchor-interval '1 hour' WHEN n=18 THEN q.anchor-interval '13 hours' ELSE NULL END,
 CASE WHEN n=19 THEN q.anchor-interval '1 hour' WHEN n=20 THEN q.anchor-interval '13 hours' ELSE NULL END,
 q.anchor-(n||' days')::interval,
 CASE WHEN n=5 THEN q.anchor-interval '1 minute' WHEN n=6 THEN q.anchor-interval '10 minutes' ELSE NULL END,
 q.anchor-interval '40 days' FROM qa_actors CROSS JOIN qa_config q;
INSERT INTO users(id,username,email,password_hash,email_verified_at,status,role,age,gender,bio,experience_years,last_login_at,created_at)
SELECT 910100+n,'QA_RELEASE_page_'||lpad(n::text,3,'0'),
 'qa-release-page-'||lpad(n::text,3,'0')||'@example.test',q.password_hash,q.anchor-interval '2 days',
 'ACTIVE','USER',20+n%50,CASE WHEN n%2=0 THEN '女性' ELSE '男性' END,'QA_RELEASE 分頁用の合成プロフィール',n%20,
 q.anchor-(n||' hours')::interval,q.anchor-interval '40 days'
FROM generate_series(1,60) s(n) CROSS JOIN qa_config q;
INSERT INTO user_parts SELECT u.id,p.id FROM users u CROSS JOIN parts p
 WHERE u.id NOT IN(910003,910024,910025) AND p.name='ギター';
INSERT INTO user_genres SELECT u.id,g.id FROM users u CROSS JOIN genres g
 WHERE u.id NOT IN(910003,910024,910025) AND g.name='ポップス';
INSERT INTO user_stances SELECT u.id,s.id FROM users u CROSS JOIN stances s
 WHERE u.id NOT IN(910003,910024,910025) AND s.name='趣味で楽しみたい';
INSERT INTO user_prefectures SELECT u.id,p.id FROM users u CROSS JOIN prefectures p
 WHERE u.id NOT IN(910003,910024,910025) AND p.name='東京都';
INSERT INTO user_prefectures SELECT 910004,id FROM prefectures WHERE name IN('大阪府','神奈川県');
UPDATE users SET profile_image_url='/uploads/97000000-0000-4000-8000-000000000001.png' WHERE id=910004;
UPDATE users SET profile_image_url='/uploads/97000000-0000-4000-8000-000000000008.png' WHERE id=910022;
INSERT INTO line_accounts(id,user_id,line_user_id,created_at)
 SELECT 990001,910025,'QA_RELEASE_LINE_SUBJECT_001',anchor FROM qa_config;
CREATE TEMP TABLE qa_posts(n integer,owner_n integer,status text,reason text) ON COMMIT DROP;
INSERT INTO qa_posts VALUES (1,5,'OPEN',NULL),(2,6,'OPEN',NULL),(3,18,'OPEN',NULL),
 (4,17,'OPEN',NULL),(5,19,'CLOSED','MANUAL'),(6,20,'CLOSED','EXPIRED'),
 (7,21,'OPEN',NULL),(8,11,'CLOSED','SUSPENDED'),(9,14,'OPEN',NULL),
 (10,9,'OPEN',NULL),(11,10,'OPEN',NULL),(12,22,'OPEN',NULL),
 (13,5,'CLOSED','MANUAL'),(14,6,'CLOSED','DELETED_BY_ADMIN');
INSERT INTO posts(id,user_id,type,title,content,area_sub,activity_frequency,status,closed_reason,created_at,updated_at,closed_at,expires_at,rank_updated_at)
SELECT 920000+n,910000+owner_n,CASE WHEN n=2 THEN 'WANTS_TO_JOIN' ELSE 'MEMBER_WANTED' END,
 'QA_RELEASE 基本投稿 '||n,CASE WHEN n=2 THEN 'QA_RELEASE 本文限定キーワード藍色セッション' ELSE 'QA_RELEASE ギターとベースで合わせたいです。' END,
 '新宿駅付近','WEEKLY_1',p.status,p.reason,q.anchor-interval '7 days',q.anchor-interval '2 days',
 CASE WHEN p.status='CLOSED' THEN q.anchor-interval '1 day' ELSE NULL END,
 CASE WHEN n=7 THEN q.anchor-interval '1 minute' ELSE q.anchor+interval '23 days' END,
 q.anchor-(n||' hours')::interval FROM qa_posts p CROSS JOIN qa_config q;
INSERT INTO posts(id,user_id,type,title,content,area_sub,activity_frequency,status,created_at,updated_at,expires_at,rank_updated_at)
SELECT 920100+n,910100+n,CASE WHEN n%2=0 THEN 'WANTS_TO_JOIN' ELSE 'MEMBER_WANTED' END,
 'QA_RELEASE PAGE '||lpad(n::text,3,'0'), 'QA_RELEASE ページング条件テスト '||n,
 CASE WHEN n%2=0 THEN '渋谷駅' ELSE '梅田駅' END,
 (ARRAY['WEEKLY_2PLUS','WEEKLY_1','MONTHLY_2_3','MONTHLY_1','BIMONTHLY_1'])[(n-1)%5+1],
 'OPEN',q.anchor-interval '7 days',q.anchor-interval '2 days',q.anchor+interval '23 days',
 q.anchor-interval '2 days'-(n||' minutes')::interval FROM generate_series(1,60)s(n) CROSS JOIN qa_config q;
INSERT INTO post_parts SELECT p.id,m.id FROM posts p CROSS JOIN parts m
 WHERE m.name=CASE WHEN p.id%2=0 THEN 'ベース' ELSE 'ギター' END;
INSERT INTO post_genres SELECT p.id,m.id FROM posts p CROSS JOIN genres m
 WHERE m.name=CASE WHEN p.id%3=0 THEN 'ジャズ' ELSE 'ポップス' END;
INSERT INTO post_stances SELECT p.id,m.id FROM posts p CROSS JOIN stances m WHERE m.name='趣味で楽しみたい';
INSERT INTO post_prefectures SELECT p.id,m.id FROM posts p CROSS JOIN prefectures m
 WHERE m.name=CASE WHEN p.id%2=0 THEN '大阪府' ELSE '東京都' END;
INSERT INTO post_age_ranges SELECT id, (ARRAY['S10','S20','S30','S40','S50_PLUS','ANY'])[(id%6)::integer+1] FROM posts;
-- Multi-valued rows expose duplicate joins and same-field OR semantics.
INSERT INTO post_parts SELECT 920001,id FROM parts WHERE name='ベース';
INSERT INTO post_prefectures SELECT 920001,id FROM prefectures WHERE name IN('大阪府','神奈川県');
INSERT INTO post_images(id,post_id,image_url,sort_order,created_at)
SELECT 980000+n,920009,'/uploads/97000000-0000-4000-8000-'||lpad((n+1)::text,12,'0')||'.png',n-1,q.anchor
FROM generate_series(1,5)s(n) CROSS JOIN qa_config q;
INSERT INTO conversations(id,user_a_id,user_b_id,created_at,last_message_at)
SELECT 930000+n,a,b,q.anchor-interval '1 day',q.anchor-(n||' minutes')::interval
FROM (VALUES(1,910007,910008),(2,910009,910010),(3,910007,910011),(4,910007,910022))v(n,a,b) CROSS JOIN qa_config q;
INSERT INTO messages(id,conversation_id,sender_id,content,image_url,created_at,read_at)
SELECT 940000+n,930000+c,s,body,img,q.anchor-(mins||' minutes')::interval,
 CASE WHEN was_read THEN q.anchor-interval '1 minute' ELSE NULL END
FROM (VALUES
 (1,1,910007,'QA_RELEASE 前文非公開',NULL,8,true),
 (2,1,910008,'QA_RELEASE 通報対象のみ','/api/messages/images/97000000-0000-4000-8000-000000000007.png',7,false),
 (3,1,910007,'QA_RELEASE 後文非公開',NULL,1,false),
 (4,2,910009,'QA_RELEASE ブロック前の会話',NULL,2,true),
 (5,3,910011,'QA_RELEASE 停止前の会話',NULL,3,false),
 (6,4,910022,'QA_RELEASE 退会で削除する会話',NULL,4,false)
)v(n,c,s,body,img,mins,was_read) CROSS JOIN qa_config q;
INSERT INTO notifications(id,user_id,type,content,related_id,created_at,read_at)
SELECT 950000+n,u,'NEW_MESSAGE','QA_RELEASE 合成の新着通知',c,q.anchor-(n||' minutes')::interval,
 CASE WHEN n=3 THEN q.anchor ELSE NULL END
FROM (VALUES(1,910008,930001),(2,910007,930001),(3,910007,930003))v(n,u,c) CROSS JOIN qa_config q;
INSERT INTO blocks(id,blocker_id,blocked_id,created_at) SELECT 960001,910009,910010,anchor FROM qa_config;
INSERT INTO reports(id,reporter_id,target_type,target_id,reason_text,status,content_snapshot,image_snapshot,created_at)
SELECT 961000+n,910007,t,target,'QA_RELEASE 合成通報理由',status,
 CASE WHEN n=1 THEN 'QA_RELEASE 通報対象のみ' ELSE NULL END,
 CASE WHEN n=1 THEN '/api/messages/images/97000000-0000-4000-8000-000000000007.png' ELSE NULL END,
 q.anchor-(n||' minutes')::interval
FROM (VALUES(1,'MESSAGE',940002,'PENDING'),(2,'POST',920001,'REVIEWED'),
 (3,'USER',910011,'ACTIONED'),(4,'POST',920002,'DISMISSED'))v(n,t,target,status) CROSS JOIN qa_config q;
INSERT INTO feedback(id,user_id,type,message_text,image_url,created_at)
SELECT 962000+n,u,t,'QA_RELEASE 合成自由記述'||E'\n'||'二行目',
 CASE WHEN n=1 THEN '/uploads/97000000-0000-4000-8000-000000000009.png' ELSE NULL END,q.anchor-(n||' minutes')::interval
FROM(VALUES(1,910004,'CONTACT'),(2,910004,'FEATURE_REQUEST'),(3,910022,'CONTACT'))v(n,u,t) CROSS JOIN qa_config q;
INSERT INTO email_verification_tokens(id,user_id,token,expires_at,used_at,created_at)
SELECT 963000+n,910001,'qa-release-verify-'||label,
 q.anchor+delta,CASE WHEN n=3 THEN q.anchor-interval '1 hour' ELSE NULL END,q.anchor-interval '2 hours'
FROM(VALUES(1,'valid',interval '24 hours'),(2,'expired',interval '-1 hour'),(3,'used',interval '24 hours'))v(n,label,delta) CROSS JOIN qa_config q;
INSERT INTO password_reset_tokens(id,user_id,token,expires_at,used_at,created_at)
SELECT 964000+n,910002,'qa-release-reset-'||label,
 q.anchor+delta,CASE WHEN n=3 THEN q.anchor-interval '1 hour' ELSE NULL END,q.anchor-interval '2 hours'
FROM(VALUES(1,'valid',interval '24 hours'),(2,'expired',interval '-1 hour'),(3,'used',interval '24 hours'))v(n,label,delta) CROSS JOIN qa_config q;
-- Advance identity sequences past reserved IDs; new records cannot collide with fixed fixtures.
DO $$ DECLARE t text; seq text; high bigint; BEGIN
 FOREACH t IN ARRAY ARRAY['users','posts','post_images','conversations','messages','notifications','blocks',
 'reports','feedback','email_verification_tokens','password_reset_tokens','line_accounts','search_histories'] LOOP
  seq:=pg_get_serial_sequence('public.'||t,'id');
  IF seq IS NULL THEN RAISE EXCEPTION 'Identity sequence missing for %',t; END IF;
  EXECUTE format('SELECT greatest(coalesce(max(id),0),1000000) FROM public.%I',t) INTO high;
  PERFORM setval(seq,high,true);
 END LOOP;
END $$;
COMMIT;
SELECT suite,anchor,manifest_version FROM qa_release_fixture;
SELECT count(*) AS users_expected_84 FROM users;
SELECT count(*) AS posts_expected_74 FROM posts;
